myshop/registration/urls.py
from django.urls import path

from . import views

app_name = 'registration'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.MyLoginView.as_view(), name='login'),
    path('logout/', views.MyLogoutView.as_view(), name='logout'),
    path('admin_dashboard/', views.AdminDashboardView.as_view(), name='admin_dashboard'),
    path('user_info/', views.MyUserInfoView.as_view(), name='user_info'),
    path('update_user_info/', views.UpdateUserInfoView.as_view(), name='update_user_info'),
]

myshop/shop_app/urls.py
from django.urls import path
from . import views

app_name = 'shop_app'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('category/<int:pk>/', views.CategoryDetailView.as_view(), name='category_detail'),
    # path('product_list/', views.ProductListView.as_view(), name='product_list'),
    path('product/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('search/', views.ProductSearchView.as_view(), name='product_search'),
    path('cart/', views.OrderListView.as_view(), name='order_list'),
    path('order/<int:pk>/', views.OrderDetailsView.as_view(), name='order_details'),
    path('add_to_cart/<int:product_pk>/', views.AddToCardView.as_view(), name='add_to_cart'),
    path('update_quantity/<int:pk>/', views.UpdateQuantityView.as_view(), name='update_quantity'),
    path('delete_order_item/<int:pk>/', views.DeleteOrderItemView.as_view(), name='delete_order_item'),
    path('checkout/', views.CheckOutView.as_view(), name='checkout'),
    path('checkout_completed/', views.CheckoutCompletedView.as_view(), name='checkout_completed'),
]

myshop/src/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop_app.urls')),
    path('auth/', include('registration.urls')),
    path('conversation/', include('conversation.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

myshop/shop_app/models.py
from django.contrib.auth.models import User
from django.contrib.postgres.indexes import GinIndex
from django.core.validators import RegexValidator
from django.db import models
from django.db.models.signals import post_delete, post_save
from django.dispatch import receiver
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchVectorField


class Category(models.Model):
    title = models.CharField(max_length=120)
    image = models.ImageField(upload_to='category_images', blank=True, null=True)

    class Meta:
        verbose_name_plural = 'Categories'
        ordering = ('title',)

    def __str__(self):
        return self.title


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    title = models.CharField(max_length=120)
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(max_digits=15, decimal_places=2)
    image = models.ImageField(upload_to='products_images', blank=True, null=True)
    available = models.BooleanField(default=True)
    search_vector = SearchVectorField(null=True)

    def search(self, query):
        query_vector = SearchQuery(query)
        return self.objects.annotate(search=SearchVector('title', 'description')).filter(search=query_vector)

    class Meta:
        indexes = [
            GinIndex(fields=['title'], opclasses=['gin_trgm_ops'], name='product_title_gin_idx'),
            GinIndex(fields=['description'], opclasses=['gin_trgm_ops'], name='product_desc_gin_idx'),
        ]
        ordering = ('category', 'title',)

    def __str__(self):
        return self.title


@receiver(post_save, sender=Product)
def update_search_vector(sender, instance, **kwargs):
    Product.objects.filter(pk=instance.pk).update(
        search_vector=SearchVector('title', 'description')
    )


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50, default='')
    last_name = models.CharField(max_length=50, default='')
    phone_number = models.CharField(
        max_length=15,
        validators=[
            RegexValidator(regex=r'^\+?1?\d{9,15}$',
                                  message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
        ],
        default='')
    email = models.EmailField(default='')
    address = models.CharField(max_length=250, default='')
    city = models.CharField(max_length=100, default='')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_completed = models.BooleanField(default=False)
    shipped = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return f"Order #(pk={self.pk}, user={self.user.username})"

    @property
    def total_price(self):
        return sum(order_item.total_price for order_item in self.order_items.all())

    def delete(self, *args, **kwargs):
        self.order_items.all().delete()
        super().delete(*args, **kwargs)


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='order_items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=15, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} x {self.product.title}"

    @property
    def total_price(self):
        return self.price * self.quantity


# @receiver(post_delete, sender=OrderItem)
# def handle_order_item_delete(sender, instance, **kwargs):
#     order = instance.order
#     if not order.order_items.exists():
#         order.delete()

myshop/shop_app/forms.py
from django import forms
from .models import Order, OrderItem, Category


class OrderForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        if user:
            self.fields['first_name'].initial = user.userprofile.first_name
            self.fields['last_name'].initial = user.userprofile.last_name
            self.fields['phone_number'].initial = user.userprofile.phone_number
            self.fields['city'].initial = user.userprofile.city
            self.fields['address'].initial = user.userprofile.address

    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'address', 'city', 'phone_number']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'address': forms.TextInput(attrs={'class': 'form-control'}),
            'city': forms.TextInput(attrs={'class': 'form-control'}),
            'phone_number': forms.TextInput(attrs={'class': 'form-control'}),
        }


class UpdateQuantityForm(forms.ModelForm):
    class Meta:
        model = OrderItem
        fields = ['quantity']
        widgets = {
            'quantity': forms.NumberInput(attrs={'class': 'form-control',
                                                 'style': 'width: 100px;'}),
        }

myshop/shop_app/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.postgres.search import TrigramSimilarity
from django.core.paginator import Paginator
from django.db.models import Prefetch
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, UpdateView, DeleteView, View, FormView, TemplateView
from django.contrib import messages

from .forms import OrderForm, UpdateQuantityForm
from .models import Category, Product, Order, OrderItem
from registration.models import UserProfile


class HomeView(ListView):
    model = Category
    template_name = 'shop_app/home.html'
    context_object_name = 'categories'


class CategoryDetailView(DetailView):
    model = Category
    template_name = 'shop_app/category_detail.html'
    context_object_name = 'category'
    paginate_by = 1

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        sort_options = {
            'price_asc': 'price',
            'price_desc': '-price'
        }
        sort_by = self.request.GET.get('sort', 'price_asc')
        sort_field = sort_options.get(sort_by, 'price')

        show_available = self.request.GET.get('show_available', False)
        if show_available:
            products = Product.objects.filter(category=self.object, available=True).order_by(sort_field)
        else:
            products = Product.objects.filter(category=self.object).order_by(sort_field)

        paginator = Paginator(products, self.paginate_by)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        context['page_obj'] = page_obj
        context['show_available'] = show_available
        return context


class ProductDetailView(DetailView):
    model = Product
    template_name = 'shop_app/product_detail.html'
    context_object_name = 'product'


class OrderListView(LoginRequiredMixin, ListView):
    """Here's get_queryset() instead of Django queryset,
    because in Django queryset you load all uncompleted orders of all users"""
    def get_queryset(self):
        return (
            Order.objects
            .filter(user=self.request.user, is_completed=False)
            .prefetch_related(
                Prefetch(
                    'order_items',
                    queryset=OrderItem.objects.select_related('product')
                )
            )
        )


class OrderDetailsView(LoginRequiredMixin, DetailView):
    model = Order
    template_name = 'shop_app/order_details.html'
    queryset = (Order.objects
                .prefetch_related(Prefetch('order_items', queryset=OrderItem.objects.select_related('product')))
                .select_related('user'))


class AddToCardView(LoginRequiredMixin, View):
    def post(self, request, product_pk):
        product = get_object_or_404(Product, pk=product_pk)
        order, created = Order.objects.get_or_create(user=request.user, is_completed=False)
        order_item, created = OrderItem.objects.get_or_create(
            order=order,
            product=product,
            defaults={'price': product.price, 'quantity': 1}
        )
        if not created:
            order_item.quantity += 1
            order_item.save()

        messages.success(request, f'{product.title} added to cart')

        return redirect('shop_app:product_detail', pk=product_pk)


class UpdateQuantityView(LoginRequiredMixin, UpdateView):
    model = OrderItem
    template_name_suffix = '_update_form'
    form_class = UpdateQuantityForm
    context_object_name = 'order_item'

    def get_success_url(self):
        return reverse('shop_app:order_list')

    def form_valid(self, form):
        order_item = self.get_object()
        quantity = form.cleaned_data['quantity']
        if quantity <= 0:
            return redirect(reverse('shop_app:delete_order_item', kwargs={'pk': order_item.pk}))
        else:
            order_item.quantity = quantity
            order_item.save()
            return super().form_valid(form)


class DeleteOrderItemView(LoginRequiredMixin, DeleteView):
    model = OrderItem
    success_url = reverse_lazy('shop_app:order_list')


class ProductSearchView(ListView):
    model = Product
    template_name = 'shop_app/product_search.html'
    context_object_name = 'products'

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            queryset = super().get_queryset().annotate(
                similarity=TrigramSimilarity('title', query) + TrigramSimilarity('description', query)
            ).filter(similarity__gt=0.3)
        else:
            queryset = Product.objects.none()
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.request.GET.get('q', '')
        if not context['query']:
            context['message'] = "Please, enter your search request"
        return context


class CheckOutView(LoginRequiredMixin, FormView):
    template_name = 'shop_app/checkout.html'
    form_class = OrderForm
    success_url = reverse_lazy('shop_app:checkout_completed')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        order = (Order.objects
                 .filter(user=self.request.user, is_completed=False)
                 .prefetch_related(
                    Prefetch('order_items', queryset=OrderItem.objects.select_related('product')))
                 .first())
        if order:
            context['order'] = order
            cart_items = order.order_items.all()
            context['cart_items'] = cart_items
            context['total_price'] = sum(item.total_price for item in cart_items)
        else:
            redirect('shop_app:order_list')
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        order = get_object_or_404(Order, user=self.request.user, is_completed=False)
        user_profile = get_object_or_404(UserProfile, user=self.request.user)
        order.first_name = form.cleaned_data['first_name']
        order.last_name = form.cleaned_data['last_name']
        order.phone_number = form.cleaned_data['phone_number']
        order.email = user_profile.email
        order.address = form.cleaned_data['address']
        order.city = form.cleaned_data['city']
        order.is_completed = True
        order.save()

        super().form_valid(form)
        return redirect('shop_app:checkout_completed')


class CheckoutCompletedView(LoginRequiredMixin, TemplateView):
    template_name = 'shop_app/checkout_completed.html'

myshop/shop_app/templates/shop_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Store{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'shop_app:home' %}">
            My Store
        </a>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'shop_app:order_list' %}" tabindex="-1"
                       aria-disabled="true">Cart</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <form method="POST" action="{% url 'registration:logout' %}">
                        {% csrf_token %}
                        <button type="submit" class="nav-link btn btn-link">Sign out</button>
                    </form>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'registration:user_info' %}" tabindex="-1" aria-disabled="true">
                        {{ request.user.username }}
                    </a>
                </li>
                {% if user.is_superuser %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'registration:admin_dashboard' %}" tabindex="-1" aria-disabled="true">Admin
                        dashboard</a>
                </li>
                {% endif %}
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'registration:login' %}" tabindex="-1" aria-disabled="true">Sign
                        in</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'registration:register' %}" tabindex="-1" aria-disabled="true">Register</a>
                </li>
                {% endif %}
            </ul>
            <form class="d-flex" method="get" action="{% url 'shop_app:product_search' %}">
                <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-light" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>

<div class="container mt-4">
    <div class="row">
        <div class="col-md-9">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>

</body>
</html>

myshop/shop_app/templates/shop_app/category_detail.html
{% extends 'shop_app/base.html' %}

{% block title %}{{ category.title }}{% endblock %}

{% block content %}
<h1>{{ category.title }}</h1>

<div class="mb-3">
    <span>Sort by:</span>
    <a href="?sort=price_asc&page=1{% if show_available %}&show_available=True{% endif %}" class="btn btn-outline-secondary btn-sm">Price (Low to High)</a>
    <a href="?sort=price_desc&page=1{% if show_available %}&show_available=True{% endif %}" class="btn btn-outline-secondary btn-sm">Price (High to Low)</a>
    <form method="get" class="form-inline">
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="checkbox" name="show_available" id="availableCheckbox" {% if show_available %}checked="checked"{% endif %}>
            <label class="form-check-label" for="availableCheckbox">Show only available products</label>
        </div>
        <input type="hidden" name="sort" value="{{ request.GET.sort }}">
        <input type="hidden" name="page" value="1">
        <button type="submit" class="btn btn-primary btn-sm ml-2">Apply</button>
    </form>
</div>

<div class="row row-cols-1 row-cols-md-3 g-4">
    {% for product in page_obj %}
    <div class="col mb-4">
        <div class="card h-100 {% if not product.available %}bg-transparent opacity-50{% endif %}">
            <div class="card-img-top" style="height: 200px;">
                {% if product.image %}
                    <img src="{{ product.image.url }}" alt="{{ product.title }}" class="card-img-top " style="height: 100%; object-fit: cover;">
                {% endif %}
            </div>
            <div class="card-body d-flex flex-column">
                <h5 class="card-title">{{ product.title }}</h5>
                <p class="card-text">{{ product.description|truncatewords:20 }}</p>
                <p class="card-text">Price: {{ product.price }}</p>
                <a href="{% url 'shop_app:product_detail' product.pk %}" class="btn btn-primary mt-auto">View Details</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

<nav aria-label="Page navigation" class="navbar navbar-light bg-light fixed-bottom">
    <div class="container-fluid justify-content-center">
        <ul class="pagination mb-0">
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page=1&sort={{ request.GET.sort }}{% if show_available %}&show_available=True{% endif %}">&laquo; First</a></li>
            {% endif %}

            {% for i in page_obj.paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="page-item active"><a class="page-link" href="#">{{ i }}</a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ i }}&sort={{ request.GET.sort }}{% if show_available %}&show_available=True{% endif %}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}&sort={{ request.GET.sort }}{% if show_available %}&show_available=True{% endif %}">Last &raquo;</a></li>
            {% endif %}
        </ul>
    </div>
</nav>
{% endblock %}

myshop/shop_app/templates/shop_app/checkout.html
{% extends 'shop_app/base.html' %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h1>Checkout</h1>
            <hr>
            {% if order %}
            <h3>Order Summary</h3>
            <table class="table">
                <thead>
                <tr>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>Price</th>
                    <th>Total</th>
                </tr>
                </thead>
                <tbody>
                {% for item in cart_items %}
                <tr>
                    <td>{{ item.product.title }}</td>
                    <td>{{ item.quantity }}</td>
                    <td>{{ item.price }}</td>
                    <td>{{ item.total_price }}</td>
                </tr>
                {% endfor %}
                </tbody>
                <tfoot>
                <tr>
                    <td colspan="3" class="text-end"><strong>Total:</strong></td>
                    <td>{{ total_price }}</td>
                </tr>
                </tfoot>
            </table>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-primary" type="submit">Place order</button>
            </form>
            {% else %}
                      {% if messages %}
                        {% for message in messages %}
                          <div class="alert alert-{{ message.tags }}">
                            {{ message }}
                          </div>
                        {% endfor %}
                      {% endif %}
                    {% endif %}
        </div>
    </div>
</div>
{% endblock %}

myshop/shop_app/templates/shop_app/checkout_completed.html
{% extends 'shop_app/base.html' %}

{% block content %}
<h1>Checkout Completed</h1>
<p>Thank you for your order!</p>
<button class="btn btn-primary"><a href="{% url 'shop_app:home' %}" style="color: white; text-decoration: none;">Continue Shopping</a></button>
<button class="btn btn-primary"><a href="{% url 'registration:user_info' %}" style="color: white; text-decoration: none;">Check Order status</a></button>
{% endblock %}

myshop/shop_app/templates/shop_app/home.html
{% extends 'shop_app/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}

<div class="row">
    <div class="col-md-2 mt-4 mb-4">
        <ul class="list-group">
            {% for category in categories %}
            <li class="list-group-item">
                <a href="{% url 'shop_app:category_detail' category.pk %}"
                   class="text-decoration-none text-dark d-block fs-5 fw-bold">
                    {{ category.title }}
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>
    <div class="col-md-8 offset-md-1 text-center">
        <div class="col-md-12">
            <h1 class="display-4">Welcome to My Store!</h1>
            <p class="lead">Discover a wide range of high-quality products at competitive prices.</p>
            <hr class="my-4">
            <p>At My Store, we are dedicated to providing you with the best online shopping experience. Whether you're
                looking for the latest fashion trends, top-notch electronics, or unique home decor, we've got you
                covered.</p>
            <p>With our user-friendly website and secure payment options, shopping has never been easier. Plus, our
                exceptional customer service ensures that you'll be satisfied with every purchase.</p>
            <p>Start exploring our extensive collection of products today and find exactly what you need. Happy
                shopping!</p>
        </div>
    </div>
</div>

{% endblock %}

myshop/shop_app/templates/shop_app/order_details.html
{% extends 'shop_app/base.html' %}

{% block content %}
<h1>Order #{{ object.id }}</h1>

<table>
    <thead>
    <tr>
        <th>Product</th>
        <th>Quantity</th>
        <th>Price</th>
        <th>Total</th>
    </tr>
    </thead>
    <tbody>
    {% for item in object.order_items.all %}
    <tr>
        <td>{{ item.product.title }}</td>
        <td>{{ item.quantity }}</td>
        <td>{{ item.price }}</td>
        <td>{{ item.total_price }}</td>
    </tr>
    {% endfor %}
    </tbody>
    <tfoot>
    <tr>
        <td colspan="3">Total:</td>
        <td>{{ object.total_price }}</td>
    </tr>
    </tfoot>
</table>
<div class="mt-4">
    {% if object.shipped %}
        <p class="text-success text-uppercase font-weight-bold">Your order is shipped</p>
    {% else %}
        <p class="text-warning text-uppercase font-weight-bold">Your order in progress</p>
    {% endif %}
</div>
{% endblock %}

myshop/shop_app/templates/shop_app/order_list.html
{% extends 'shop_app\base.html' %}

{% block content %}
<h1>Cart</h1>

{% if object_list %}
<table>
    <thead>
    <tr>
        <th>Product</th>
        <th>Quantity</th>
        <th>Price</th>
        <th>Total</th>
    </tr>
    </thead>
    <tbody>
    {% for order in object_list %}
    {% for item in order.order_items.all %}
    <tr>
        <td>{{ item.product.title }}</td>
        <td>{{ item.quantity }}</td>
        <td>{{ item.price }}</td>
        <td>{{ item.total_price }}</td>
        <td>
            <a href="{% url 'shop_app:update_quantity' item.pk %}" class="btn btn-primary">Update</a>
            <a href="{% url 'shop_app:delete_order_item' item.pk %}" class="btn btn-danger">Delete</a>
        </td>
    </tr>
    {% endfor %}
    </tbody>
    <tfoot>
    <tr>
        <td colspan="3">Total:</td>
        <td>{{ order.total_price }}</td>
    </tr>
    {% endfor %}
    </tfoot>
</table>
<a href="{% url 'shop_app:checkout' %}" class="btn btn-success">Proceed to Checkout</a>


{% else %}
<p>Your cart is empty.</p>
{% endif %}
{% endblock %}

myshop/shop_app/templates/shop_app/orderitem_confirm_delete.html
{% extends 'shop_app/base.html' %}

{% block content %}
    <h2>Are you sure you want to delete "{{ order_item.product.title }}"?</h2>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete</button>
        <a href="{% url 'shop_app:order_list' %}" class="btn btn-secondary">Cancel</a>
    </form>
{% endblock %}

myshop/shop_app/templates/shop_app/orderitem_update_form.html
{% extends 'shop_app/base.html' %}

{% block content %}
  <h2>Update Quantity for "{{ order_item.product.title }}"</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Update</button>
    <a href="{% url 'shop_app:order_list' %}" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

myshop/shop_app/templates/shop_app/pagination.html
<nav aria-label="Page navigation">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1">Previous</a>
      </li>
    {% endif %}

    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="page-item active">
          <a class="page-link" href="#">{{ i }} <span class="sr-only">(current)</span></a>
        </li>
      {% else %}
        <li class="page-item">
          <a class="page-link" href="?page={{ i }}">{{ i }}</a>
        </li>
      {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#">Next</a>
      </li>
    {% endif %}
  </ul>
</nav>

myshop/shop_app/templates/shop_app/product_detail.html
{% extends 'shop_app/base.html' %}

{% block title %}{{ product.title }}{% endblock %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-md-4">
            {% if product.image %}
            <img src="{{ product.image.url }}" alt="{{ product.title }}" class="card-img-top img-fluid">
            {% endif %}
        </div>
        <div class="col-md-8">
            <h3>{{ product.title }}</h3>
            <p>{{ product.description }}</p>
            <p><strong>Price: {{ product.price }}</strong></p>
        </div>
    </div>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li
        {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <div class="row mt-4">
        <div class="col text-center">
            <form action="{% url 'shop_app:add_to_cart' product.pk %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ request.path }}">
                <button type="submit" class="btn btn-primary">Add to cart</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

myshop/shop_app/templates/shop_app/product_list.html
<!-- Вставте цю частину коду в потрібне місце вашого шаблону product_list.html -->
<!--<form method="get">-->
<!--    {{ filter_form.as_p }}-->
<!--    <button type="submit" class="btn btn-primary">Фільтрувати</button>-->
<!--</form>-->

myshop/shop_app/templates/shop_app/product_search.html
{% extends 'shop_app/base.html' %}

{% block content %}


{% if message %}
    <p>{{ message }}</p>
{% endif %}

{% if products %}
    <h2>Search results for "{{ query }}"</h2>
    <ul>
        {% for product in products %}
            <li><a href="{% url 'shop_app:product_detail' pk=product.pk %}">{{ product.title }}</a></li>
        {% endfor %}
    </ul>
{% elif query %}
    <p>No results found for "{{ query }}".</p>
{% endif %}

{% endblock %}